---
- name: Debian - Install docker pre-req.
  ansible.builtin.apt:
    update_cache: true
    name:
      - ca-certificates 
      - curl 
      - gnupg
    state: present

- name: Debian - Download the docker gpg key.
  ansible.builtin.shell: 'mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && chmod a+r /etc/apt/keyrings/docker.gpg'
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Debian - Gets the last version of the repo.
  ansible.builtin.shell: 'mkdir -p /etc/ansible/facts.d && echo "{\"dockerrepoversion\": \"deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable\"}" > /etc/ansible/facts.d/dockerrepo.fact && echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable"'
  register: dockerrepo
  when: ansible_facts['ansible_local']['dockerrepo']['dockerrepoversion'] is undefined

- name: Debian - Add Docker repository - First run.
  ansible.builtin.apt_repository:
    repo: "{{ ansible_facts['ansible_local']['dockerrepo']['dockerrepoversion'] }}"
    state: present
  when: ansible_facts['ansible_local']['dockerrepo']['dockerrepoversion'] is defined

- name: Debian - Add Docker repository - Not first run.
  ansible.builtin.apt_repository:
    repo: "{{ dockerrepo.stdout }}"
    state: present
  when: ansible_facts['ansible_local']['dockerrepo']['dockerrepoversion'] is undefined
   
- name: Debian - Install docker.
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce=5:20.10.24~3-0~debian-bullseye
      - docker-ce-cli=5:20.10.24~3-0~debian-bullseye
      - containerd.io
    state: present