---
- name: Install docker pre-req.
  ansible.builtin.apt:
    update_cache: true
    name:
      - ca-certificates 
      - curl 
      - gnupg
    state: present

- name: Download the docker gpg key.
  ansible.builtin.shell: 'mkdir -p /etc/apt/keyrings & curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg & chmod a+r /etc/apt/keyrings/docker.gpg'

- name: Gets the last version of the repo.
  ansible.builtin.shell: 'echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable"'
  register: dockerrepo

- name: Add Docker repository.
  ansible.builtin.apt_repository:
    repo: "{{ dockerrepo.stdout }}"
    state: present
