---
# Playbook for rancher install
- name: Install Rancher and pre-requisites in all nodes.
  hosts: all
  gather_facts: yes
  become: true
  roles:
    # - {role: firewall, tags: security}
    - {role: docker, tags: pre-requisite}
