apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["haproxy/haproxy"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2023-05-15T07:20:16Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"6f3af5ac-cc85-4dc0-9627-fd82d03357e0"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: '2023-05-16T10:18:02Z'
  name: haproxy
  namespace: haproxy
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: haproxy
      uid: 6f3af5ac-cc85-4dc0-9627-fd82d03357e0
  resourceVersion: '497735'
  uid: 1ce4aed7-7351-4e84-b817-e3b39498b625
spec:
  clusterIP: 10.43.197.131
  clusterIPs:
    - 10.43.197.131
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: haproxy-http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: haproxy-https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-haproxy-haproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
