---
# tasks file for cert-manager
- name: Add cert-manager repo.
  kubernetes.core.helm_repository:
    binary_path: /home/rancher/.local/bin/helm
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy cert-manager.
  kubernetes.core.helm:
    binary_path: /home/rancher/.local/bin/helm
    atomic: true
    update_repo_cache: true
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    chart_version: v1.11.0
    create_namespace: true
    set_values:
      - value: installCRDs=true
        value_type: raw